import assert from 'node:assert/strict';
import fs from 'node:fs';
import {parseEnvironment,ground,buildingInside,buildingBase,losProfile} from './lib/environment-model.ts';
import {environmentMeshes,losMeshes} from './lib/environment-geometry.ts';
import {createPortfolio} from './lib/site-model.ts';
import {networkLinks} from './lib/private-network.ts';
import {disposeObject} from './lib/site-geometry.ts';
const env=parseEnvironment(JSON.parse(fs.readFileSync('public/data/austin-terrain.json')),JSON.parse(fs.readFileSync('public/data/austin-buildings.json')));assert.equal(env.terrain.elevations.length,8181);assert.equal(env.buildings.length,2043);assert.equal(env.buildings.filter(b=>b.height===null).length,5);assert(Math.abs(ground(env.terrain,0,0)-148.46)<.1);assert.equal(ground(env.terrain,9000,0),null);const model=environmentMeshes(env);assert.equal(model.buildings.children.length,1);const buildingGeometry=model.buildings.children[0].geometry;assert.equal(new Set(buildingGeometry.getAttribute('buildingId').array).size,env.buildings.filter(b=>buildingBase(env.terrain,b)!==null).length);for(const group of [model.terrain,model.buildings]){group.traverse(o=>{if(o.geometry)for(const n of o.geometry.attributes.position.array)assert(Number.isFinite(n));});disposeObject(group);}
const portfolio=createPortfolio();for(const link of networkLinks.filter(l=>l.kind==='microwave')){const profile=losProfile(env,link,portfolio);assert(profile.samples.length>20);assert(Number.isFinite(profile.clearance));assert.equal(profile.samples[0].ray,profile.a.y);assert.equal(profile.samples.at(-1).ray,profile.b.y);assert.equal(profile.samples[0].fresnel,0);assert.equal(profile.samples.at(-1).fresnel,0);const graphics=losMeshes(profile,env.terrain.reference);assert(graphics.children.length>=2);disposeObject(graphics);console.log(`${link.id}: ${profile.status}, clearance ${profile.clearance.toFixed(1)} m`);}
const b={id:1,height:10,rings:[[[0,0],[10,0],[10,10],[0,10],[0,0]],[[4,4],[6,4],[6,6],[4,6],[4,4]]]};assert(buildingInside(b,1,1));assert(!buildingInside(b,5,5));assert(!buildingInside(b,20,20));const t={...env.terrain,minX:0,minZ:0,width:2,height:2,step:10,elevations:[0,10,10,20]};assert.equal(ground(t,5,5),10);console.log('PASS: official dataset counts, units, grid interpolation, building holes, finite 3D terrain/buildings and all seven LoS profiles.');
const link=networkLinks.find(l=>l.kind==='microwave'),flat={...env,terrain:{...env.terrain,minX:-2000,minZ:-2000,width:2,height:2,step:4000,elevations:[0,0,0,0]},buildings:[]};const clear=losProfile(flat,link,portfolio);assert(clear.clearance>0);const mx=(clear.a.x+clear.b.x)/2,mz=(clear.a.z+clear.b.z)/2,narrow={id:99,height:500,rings:[[[mx-.1,mz-.1],[mx+.1,mz-.1],[mx+.1,mz+.1],[mx-.1,mz+.1],[mx-.1,mz-.1]]]};assert.equal(losProfile({...flat,buildings:[narrow]},link,portfolio).status,'Blocked');assert.equal(losProfile({...flat,buildings:[{...narrow,height:null}]},link,portfolio).status,'Unknown heights');assert.throws(()=>losProfile(flat,link,portfolio,0),/positive/);console.log('PASS: sub-metre building intersections cannot be skipped, unknown heights prevent clear status, frequency validation.');
