import {build} from 'esbuild';
import {JSDOM} from 'jsdom';
import assert from 'node:assert/strict';
const dom=new JSDOM('<html><body></body></html>',{url:'http://localhost'});
for(const key of ['window','document','navigator','HTMLElement','Element','Node','MutationObserver'])Object.defineProperty(globalThis,key,{value:dom.window[key],configurable:true});
globalThis.IS_REACT_ACT_ENVIRONMENT=true;
await build({entryPoints:['components/twin/fullscreen-button.tsx'],outfile:'.test-fullscreen-bundle.mjs',bundle:true,platform:'node',format:'esm',packages:'external',jsx:'automatic'});
const React=await import('react');
const {render,screen,fireEvent,waitFor,cleanup}=await import('@testing-library/react');
const {default:Button}=await import('./.test-fullscreen-bundle.mjs');
const mount=()=>render(React.createElement('section',{className:'twin-viewer'},React.createElement(Button,{target:'.twin-viewer',label:'3D site'})));
mount();fireEvent.click(screen.getByRole('button',{name:'Enter 3D site fullscreen'}));
await waitFor(()=>assert.ok(document.querySelector('.expanded-view')));
fireEvent.keyDown(window,{key:'Escape'});
assert.equal(document.querySelector('.expanded-view'),null);assert.equal(document.body.className,'');assert.equal(screen.queryByText(/Expanded view active/),null);
fireEvent.click(screen.getByRole('button',{name:'Enter 3D site fullscreen'}));
await waitFor(()=>assert.ok(document.querySelector('.expanded-view')));cleanup();assert.equal(document.body.className,'');
HTMLElement.prototype.requestFullscreen=async function(){Object.defineProperty(document,'fullscreenElement',{value:this,configurable:true});document.dispatchEvent(new window.Event('fullscreenchange'));};
document.exitFullscreen=async()=>{Object.defineProperty(document,'fullscreenElement',{value:null,configurable:true});document.dispatchEvent(new window.Event('fullscreenchange'));};
mount();fireEvent.click(screen.getByRole('button',{name:'Enter 3D site fullscreen'}));await waitFor(()=>assert.ok(screen.getByRole('button',{name:'Exit 3D site fullscreen'})));
assert.equal(document.fullscreenElement,document.querySelector('.twin-viewer'));
fireEvent.click(screen.getByRole('button',{name:'Exit 3D site fullscreen'}));await waitFor(()=>assert.ok(screen.getByRole('button',{name:'Enter 3D site fullscreen'})));assert.equal(document.fullscreenElement,null);cleanup();
console.log('Fullscreen native API, expanded fallback, Escape and cleanup passed.');
