import assert from 'node:assert/strict';
import fs from 'node:fs';
import {IfcAPI,IFCPROJECT,IFCSITE,IFCBUILDINGELEMENTPROXY,IFCANNOTATION,IFCPROPERTYSET,IFCRELCONNECTSPORTS} from 'web-ifc';
import {createPortfolio} from './lib/site-model.ts';
import {exportPortfolioIfc} from './lib/ifc-export.ts';
import {parseEnvironment,ground} from './lib/environment-model.ts';
import {siteWorldPosition} from './lib/network-geometry.ts';
import {networkLinks} from './lib/private-network.ts';
import {externalCable} from './lib/cabling.ts';
const env=parseEnvironment(JSON.parse(fs.readFileSync('public/data/austin-terrain.json')),JSON.parse(fs.readFileSync('public/data/austin-buildings.json'))),portfolio=createPortfolio(),text=await exportPortfolioIfc(portfolio,env),api=new IfcAPI();await api.Init();const id=api.OpenModel(new TextEncoder().encode(text),{COORDINATE_TO_ORIGIN:false});assert(id>=0);const rows=type=>{const ids=api.GetLineIDsWithType(id,type);return Array.from({length:ids.size()},(_,i)=>api.GetLine(id,ids.get(i),true));};
assert.equal(rows(IFCPROJECT).length,1);const sites=rows(IFCSITE),proxies=rows(IFCBUILDINGELEMENTPROXY),annotations=rows(IFCANNOTATION),properties=rows(IFCPROPERTYSET).filter(p=>p.Name.value==='Citymesh_Environment');assert.equal(sites.length,30);assert.equal(proxies.length,30+2038+1);assert.equal(annotations.length,7+5);assert.equal(properties.length,2044);const terrain=proxies.find(p=>p.Tag.value==='austin:usgs:terrain'),points=terrain.Representation.Representations[0].Items[0].Coordinates.CoordList;assert.equal(points.length,8181);assert(Math.abs(points[0][2].value-env.terrain.elevations[0])<1e-5);assert(Math.abs(points.at(-1)[2].value-env.terrain.elevations.at(-1))<1e-5);
for(const site of sites){const p=Object.values(portfolio).find(p=>p.name===site.Name.value);assert(p);const origin=siteWorldPosition(p.siteId);assert(Math.abs(site.ObjectPlacement.RelativePlacement.Location.Coordinates[2].value-ground(env.terrain,origin.x,origin.z))<1e-7);}
for(const b of env.buildings){const pset=properties.find(p=>p.HasProperties.some(v=>v.Name.value==='SourceObjectId'&&v.NominalValue.value===String(b.id)));assert(pset);if(b.height===null){assert(pset.HasProperties.some(p=>p.Name.value==='HeightMetres'&&p.NominalValue.value==='Unknown'));continue;}const proxy=proxies.find(p=>p.Tag.value==='austin:building:'+b.id);assert(proxy);const xyz=proxy.Representation.Representations[0].Items[0].Coordinates.CoordList,heights=xyz.map(v=>v[2].value);assert(Math.abs(Math.max(...heights)-Math.min(...heights)-b.height)<.0001);}
const connections=rows(IFCRELCONNECTSPORTS);for(const link of networkLinks){const connection=connections.find(c=>c.Name.value===link.id),cable=externalCable(link,portfolio);for(const [port,end] of [[connection.RelatingPort,cable.from],[connection.RelatedPort,cable.to]]){const base=siteWorldPosition(end.siteId),actual=port.ObjectPlacement.RelativePlacement.Location.Coordinates[2].value+port.ObjectPlacement.PlacementRelTo.RelativePlacement.Location.Coordinates[2].value;assert(Math.abs(actual-ground(env.terrain,base.x,base.z)-end.position[1])<1e-7);}}
const stripped=text.replace(/'(?:''|[^'])*'/g,"''"),ids=[...stripped.matchAll(/^#(\d+)=/gm)].map(m=>m[1]),set=new Set(ids);assert.equal(ids.length,set.size);for(const m of stripped.matchAll(/#(\d+)/g))assert(set.has(m[1]));api.CloseModel(id);console.log(`PASS: ${Math.round(text.length/1024/1024)} MB context IFC with 30 elevated sites, all terrain samples, 2038 height-bearing buildings, five unknown-height annotations, source metadata and correct transport endpoint elevations.`);
