import assert from 'node:assert/strict';
import {IfcAPI,IFCBUILDINGELEMENTPROXY,IFCPROJECT,IFCSITE,IFCDISTRIBUTIONELEMENT,IFCDISTRIBUTIONPORT,IFCCABLESEGMENT,IFCANNOTATION,IFCRELCONNECTSPORTS,IFCRELNESTS,IFCRELAGGREGATES,IFCPROPERTYSET} from 'web-ifc';
import {createPortfolio} from './lib/site-model.ts';
import {exportPortfolioIfc} from './lib/ifc-export.ts';
import {siteWorldPosition} from './lib/network-geometry.ts';
import {networkLinks} from './lib/private-network.ts';
import {externalCable} from './lib/cabling.ts';
const p=createPortfolio();p['GBT-01'].equipment[0].name="Antenna #8 'quoted' Ω";const text=await exportPortfolioIfc(p),api=new IfcAPI();await api.Init();const id=api.OpenModel(new TextEncoder().encode(text),{COORDINATE_TO_ORIGIN:false});assert(id>=0);
const rows=type=>{const ids=api.GetLineIDsWithType(id,type);return Array.from({length:ids.size()},(_,i)=>api.GetLine(id,ids.get(i),true));};
const structures=rows(IFCBUILDINGELEMENTPROXY);assert.equal(structures.length,30);for(const s of structures){const body=s.Representation.Representations[0];assert.equal(body.RepresentationType.value,'Tessellation');assert(body.Items[0].Coordinates.CoordList.length>0);assert(body.Items[0].CoordIndex.length>0);}
const projects=rows(IFCPROJECT),sites=rows(IFCSITE),elements=rows(IFCDISTRIBUTIONELEMENT),cables=rows(IFCCABLESEGMENT),annotations=rows(IFCANNOTATION),ports=rows(IFCDISTRIBUTIONPORT),connections=rows(IFCRELCONNECTSPORTS),nests=rows(IFCRELNESTS),aggregates=rows(IFCRELAGGREGATES),props=rows(IFCPROPERTYSET);
assert.equal(projects.length,1);assert.equal(sites.length,30);assert.equal(elements.length,374);assert.equal(cables.length,662);assert.equal(annotations.length,0);assert.equal(ports.length,1324);assert.equal(connections.length,662);assert.equal(nests.length,1324);assert.equal(aggregates.length,30);assert(aggregates.every(r=>r.RelatingObject.expressID===projects[0].expressID));assert(elements.some(e=>e.Name.value==="Antenna #8 'quoted' Ω"));
for(const site of sites){const property=props.find(s=>s.Name.value==='Citymesh_Location'&&s.HasProperties.some(v=>v.Name.value==='SiteId'&&p[v.NominalValue?.value]?.name===site.Name.value));assert(property);const siteId=property.HasProperties.find(v=>v.Name.value==='SiteId').NominalValue.value,expected=siteWorldPosition(siteId),xyz=site.ObjectPlacement.RelativePlacement.Location.Coordinates.map(n=>n.value);assert.deepEqual(xyz,[expected.x,-expected.z,0]);}
for(const l of networkLinks){const connection=connections.find(r=>r.Name.value===l.id),wireless=l.kind==='microwave',source=externalCable(l,p);assert(connection);if(wireless)assert.equal(connection.RealizingElement,null);else assert.equal(connection.RealizingElement.Tag.value,l.id);for(const [port,end] of [[connection.RelatingPort,source.from],[connection.RelatedPort,source.to]]){const local=port.ObjectPlacement.RelativePlacement.Location.Coordinates.map(v=>v.value),parent=port.ObjectPlacement.PlacementRelTo.RelativePlacement.Location.Coordinates.map(v=>v.value),offset=siteWorldPosition(end.siteId);assert(Math.abs(local[0]+parent[0]-offset.x-end.position[0])<1e-6);assert(Math.abs(local[1]+parent[1]+offset.z+end.position[2])<1e-6);assert(Math.abs(local[2]-end.position[1])<1e-6);assert.equal(port.Name.value,wireless?end.port:`${end.port} / trunk`);}}
const withoutStrings=text.replace(/'(?:''|[^'])*'/g,"''"),defined=new Set([...withoutStrings.matchAll(/^#(\d+)=/gm)].map(m=>m[1]));for(const m of withoutStrings.matchAll(/#(\d+)/g))assert(defined.has(m[1]),'Dangling STEP reference '+m[1]);
const usage=new Map();for(const c of connections)for(const port of [c.RelatingPort,c.RelatedPort])usage.set(port.expressID,(usage.get(port.expressID)||0)+1);assert([...usage.values()].every(n=>n===1));const guids=[...structures,...projects,...sites,...elements,...cables,...annotations,...ports,...connections,...nests,...aggregates,...props].map(o=>o.GlobalId.value);assert.equal(guids.length,new Set(guids).size);api.CloseModel(id);const missing={...p};delete missing['GBT-01'];await assert.rejects(()=>exportPortfolioIfc(missing),/all 30/);const deleted=createPortfolio();deleted['GBT-01'].equipment=deleted['GBT-01'].equipment.filter(e=>e.id!=='CAB-01');await assert.rejects(()=>exportPortfolioIfc(deleted),/missing site termination/);console.log('PASS: one IFC project, 30 coordinated sites, 374 equipment/fixtures, 662 physical cables, 0 wireless annotations, 1324 uniquely connected ports, 662 relationships, endpoint transforms, GUIDs and quoted reference safety.');
