import {build} from 'esbuild';
import {JSDOM} from 'jsdom';
import assert from 'node:assert/strict';
import path from 'node:path';
import fs from 'node:fs';
import {pathToFileURL} from 'node:url';
const dom=new JSDOM('<!doctype html><html><body></body></html>',{url:'http://localhost/sites',pretendToBeVisual:true});
for(const key of ['window','document','navigator','HTMLElement','Element','Node','MutationObserver','HTMLInputElement','HTMLTextAreaElement','getComputedStyle','localStorage','FormData','Event','MouseEvent','File'])Object.defineProperty(globalThis,key,{value:dom.window[key],configurable:true,writable:true});
window.PointerEvent=window.MouseEvent;globalThis.PointerEvent=window.MouseEvent;globalThis.IS_REACT_ACT_ENVIRONMENT=true;
globalThis.ResizeObserver=class{observe(){}unobserve(){}disconnect(){}};
globalThis.requestAnimationFrame=cb=>setTimeout(cb,0);globalThis.cancelAnimationFrame=clearTimeout;
window.matchMedia=()=>({matches:false,addEventListener(){},removeEventListener(){}});
Element.prototype.scrollIntoView=function(){};
await build({entryPoints:['app/page.tsx'],outfile:'.test-network-bundle.mjs',bundle:true,platform:'node',format:'esm',packages:'external',jsx:'automatic',loader:{'.css':'empty'},plugins:[{name:'isolated-controls',setup(b){b.onResolve({filter:/^next\/link$/},()=>({path:'link',namespace:'stub'}));b.onResolve({filter:/network-viewer$/},()=>({path:'network',namespace:'stub'}));b.onResolve({filter:/site-viewer$/},()=>({path:'viewer',namespace:'stub'}));b.onLoad({filter:/.*/,namespace:'stub'},args=>({resolveDir:process.cwd(),loader:'jsx',contents:args.path==='network'?"import React from 'react'; export default function NetworkViewer(p){return <div><button onClick={()=>p.onAsset('GBT-01','ANT-B')}>Pick antenna adapter</button><button onClick={()=>p.onCable('GBT-01','GBT-01/RF-ANT-B')}>Pick jumper adapter</button></div>;}":args.path==='link'?`import React from 'react'; export default function Link(props){return <a {...props}/>;}`:`import React from 'react'; export default function Viewer({equipment,selected,onSelect,siteType}){return <div aria-label="3D model adapter"><span data-testid="site-model-type">{siteType}</span>{equipment.map(e=><button key={e.id} onClick={()=>onSelect(e.id)}>{e.id}</button>)}<output data-testid="selected-asset">{selected}</output></div>;}`}));}}]});
const React=await import('react');const {render,screen,fireEvent,cleanup,waitFor}=await import('@testing-library/react');const {default:Sites}=await import(pathToFileURL(path.resolve('.test-network-bundle.mjs')).href);

const originalFetch=globalThis.fetch;globalThis.fetch=(url,...args)=>String(url).startsWith('/data/austin-')?Promise.resolve(new Response(fs.readFileSync('public'+url,'utf8'),{status:200,headers:{'Content-Type':'application/json'}})):originalFetch(url,...args);
render(React.createElement(Sites));fireEvent.click(screen.getByRole('button',{name:'Flat map'}));assert.ok(screen.getByRole('heading',{name:'One network. Every site connected.'}));assert.equal(screen.getAllByRole('row').length,31);assert.ok(document.querySelectorAll('.circuit-trace li').length>5);fireEvent.click(document.querySelector('.cable-list button'));assert.ok(document.querySelector('.cable-detail').textContent.includes('LC/UPC'));
const savedCreate=URL.createObjectURL,savedRevoke=URL.revokeObjectURL,savedClick=window.HTMLAnchorElement.prototype.click;let savedBlob,downloadName;
URL.createObjectURL=blob=>{savedBlob=blob;return 'blob:test-bim';};URL.revokeObjectURL=()=>{};window.HTMLAnchorElement.prototype.click=function(){downloadName=this.download;};
fireEvent.click(screen.getByRole('button',{name:'Export connected BIM · IFC4'}));await waitFor(()=>assert.ok(screen.getByText('IFC4 exported with equipment, cable axes, distribution ports and connection relationships.')));assert.equal(downloadName,'GBT-01-equipment-and-cabling.ifc');assert.ok((await savedBlob.text()).includes('IFCRELCONNECTSPORTS('));fireEvent.click(screen.getByRole('button',{name:'Export 30-site BIM'}));await waitFor(()=>assert.ok(screen.getByText('Coordinated IFC4 exported: all 30 sites, local cabling and 38 transport paths. Microwave paths are wireless annotations.')),{timeout:15000});assert.equal(downloadName,'citymesh-austin-30-sites.ifc');assert.ok((await savedBlob.text()).includes('IFCANNOTATION('));URL.createObjectURL=savedCreate;URL.revokeObjectURL=savedRevoke;window.HTMLAnchorElement.prototype.click=savedClick;
fireEvent.click(screen.getByRole('button',{name:'Pick antenna adapter'}));assert.ok(screen.getByRole('heading',{name:'Sector B antenna'}));assert.equal(screen.getByRole('link',{name:'Open asset workspace'}).getAttribute('href'),'/sites?site=GBT-01&asset=ANT-B');assert.ok(document.querySelector('.circuit-trace').textContent.includes('GBT-01/ANT-B'));fireEvent.click(screen.getByRole('button',{name:'Pick jumper adapter'}));assert.ok(document.querySelector('.network-inspector .cable-detail').textContent.includes('4.3-10'));
const physicalLinks=screen.getAllByRole('link').map(a=>a.getAttribute('href')).filter(h=>h?.startsWith('/sites?site='));assert.equal(new Set(physicalLinks.map(h=>h.split('&')[0])).size,30);
fireEvent.click(screen.getByRole('button',{name:'IBS-01 Assembly hall',exact:true}));assert.equal(screen.getByRole('link',{name:'Inspect 3D site'}).getAttribute('href'),'/sites?site=IBS-01');
fireEvent.click(screen.getByRole('button',{name:'Simulate complete site outage'}));assert.equal(document.querySelector('.network-detail .site-health').textContent,'Disconnected');assert.ok(document.querySelector('.trace-warning').textContent.includes('No transport path'));
fireEvent.click(screen.getByRole('button',{name:'Restore simulated site'}));assert.notEqual(document.querySelector('.network-detail .site-health').textContent,'Disconnected');assert.equal(document.querySelector('.trace-warning'),null);
fireEvent.click(screen.getByRole('button',{name:'2D topology'}));fireEvent.click(screen.getByRole('button',{name:/^L01:/}));fireEvent.click(screen.getByRole('button',{name:'Simulate link failure'}));assert.ok(screen.getByText('Offline',{exact:true,selector:'dd'}));fireEvent.click(screen.getByRole('button',{name:'Restore transport link'}));assert.ok(screen.getByText('Available',{exact:true,selector:'dd'}));
fireEvent.change(screen.getByRole('textbox',{name:'Search network sites'}),{target:{value:'IBS-'}});assert.equal(screen.getAllByRole('row').length,11);
fireEvent.click(screen.getByRole('button',{name:'Select GBT-03 geographic site'}));assert.ok(screen.getByRole('heading',{name:'GBT-03 · RF parameters'}));const oldRadius=document.querySelector('.rf-kpis').textContent;fireEvent.change(screen.getByRole('spinbutton',{name:'TX power (dBm)'}),{target:{value:'40'}});assert.notEqual(document.querySelector('.rf-kpis').textContent,oldRadius);assert.equal(JSON.parse(localStorage.getItem('citymesh-rf-v1'))['GBT-03'].power,40);fireEvent.click(screen.getByRole('checkbox',{name:'coverage',exact:true}));assert.equal(document.querySelectorAll('.geo-map polygon').length,0);fireEvent.click(screen.getByRole('checkbox',{name:'coverage',exact:true}));assert.equal(document.querySelectorAll('.geo-map polygon').length,330);fireEvent.click(screen.getByRole('button',{name:'Reset this site RF'}));assert.equal(screen.getByRole('spinbutton',{name:'TX power (dBm)'}).value,'30');
await waitFor(()=>assert.ok(screen.getByRole('heading',{name:'Microwave LoS & path elevation'})));const priorProfile=document.querySelector('.los-panel>p').textContent;fireEvent.change(screen.getByRole('spinbutton',{name:'Frequency (GHz)'}),{target:{value:'6'}});assert.notEqual(document.querySelector('.los-panel>p').textContent,priorProfile);fireEvent.change(screen.getByRole('combobox',{name:'Path'}),{target:{value:'L37'}});assert.equal(screen.getByRole('combobox',{name:'Path'}).value,'L37');const losToggle=screen.getByRole('checkbox',{name:'Apply modeled microwave LoS'});await waitFor(()=>assert.equal(losToggle.disabled,false));assert.equal(losToggle.checked,false);fireEvent.click(losToggle);assert.ok(document.querySelector('.los-simulation output').textContent.includes('30 → 27'));fireEvent.click(screen.getByRole('button',{name:'Reset network scenarios'}));assert.equal(losToggle.checked,false);assert.equal(document.querySelector('.los-simulation output'),null);globalThis.fetch=originalFetch;
const style=document.createElement('style');style.textContent=fs.readFileSync('app/network.css','utf8')+fs.readFileSync('components/twin/cabling.css','utf8');document.head.appendChild(style);const layerIcon=document.querySelector('.network-layers summary svg'),iconStyle=window.getComputedStyle(layerIcon);assert.equal(iconStyle.width,'13px');assert.equal(iconStyle.minWidth,'0');assert.equal(iconStyle.minHeight,'0');assert.equal(document.querySelector('.network-layers').open,false);assert.equal(document.querySelectorAll('.network-map .network-topology').length,1);style.remove();
cleanup();dom.window.close();console.log('Network control integration passed: all 30 physical-twin links, site selection, site outage/restore, transport outage/restore, and IBS portfolio search. Type-selection popup layout is not verified by this jsdom check.');








