import {build} from 'esbuild';
import {JSDOM} from 'jsdom';
import assert from 'node:assert/strict';
import {pathToFileURL} from 'node:url';
import path from 'node:path';
import {photoBytes} from './photo.test.mjs';
import {listPhotos} from './lib/photo-store.ts';
import {createPortfolio} from './lib/site-model.ts';
const dom=new JSDOM('<!doctype html><html><body></body></html>',{url:'http://localhost/sites'});
for(const k of ['window','document','navigator','HTMLElement','Element','Node','MutationObserver','FormData','Event','MouseEvent'])Object.defineProperty(globalThis,k,{value:dom.window[k],configurable:true,writable:true});
globalThis.IS_REACT_ACT_ENVIRONMENT=true;let rejectDecode=false;globalThis.createImageBitmap=async()=>{if(rejectDecode)throw Error('Invalid image encoding');return {width:1,height:1,close(){}};};
const downloads=[];dom.window.HTMLAnchorElement.prototype.click=function(){downloads.push(this.download);};
await build({entryPoints:['components/twin/photo-panel.tsx'],outfile:'.test-photo-bundle.mjs',bundle:true,platform:'node',format:'esm',packages:'external',jsx:'automatic',loader:{'.css':'empty'}});
const React=await import('react'),{render,screen,fireEvent,cleanup,waitFor}=await import('@testing-library/react'),{default:Panel}=await import(pathToFileURL(path.resolve('.test-photo-bundle.mjs')).href);
let located='';const props={siteId:'GBT-01',revision:2,equipment:createPortfolio()['GBT-01'].equipment,selected:'ANT-A',onSelect:id=>located=id};
render(React.createElement(Panel,props));await waitFor(()=>assert.equal(screen.getByLabelText('Attach component photo').disabled,false));
fireEvent.change(screen.getByLabelText('Photo source'),{target:{value:'Inspection team'}});fireEvent.change(screen.getByLabelText('Photo capture date'),{target:{value:'2026-09-06'}});
const upload=()=>fireEvent.change(screen.getByLabelText('Attach component photo'),{target:{files:[{name:'field.png',size:photoBytes.byteLength,arrayBuffer:async()=>photoBytes.slice(0)}]}});
upload();await waitFor(()=>assert.ok(screen.getByText('Photo saved for ANT-A.')));assert.equal((await listPhotos('GBT-01'))[0].revision,2);assert.equal((await listPhotos('GBT-01'))[0].source,'Inspection team');
fireEvent.click(screen.getByRole('button',{name:'Locate component'}));assert.equal(located,'ANT-A');fireEvent.click(screen.getByRole('button',{name:'Download original'}));assert.equal(downloads.at(-1),'field.png');
cleanup();render(React.createElement(Panel,{...props,selected:'RRU-A'}));await waitFor(()=>assert.ok(screen.getByText('field.png')));fireEvent.click(screen.getByRole('button',{name:'Selected component'}));assert.ok(screen.getByText('No photos saved for this component.'));fireEvent.click(screen.getByRole('button',{name:'All site photos'}));
rejectDecode=true;upload();await waitFor(()=>assert.ok(screen.getByText('Invalid image encoding')));assert.equal((await listPhotos('GBT-01')).length,1);
fireEvent.click(screen.getByRole('button',{name:'Remove photo'}));fireEvent.click(screen.getByRole('button',{name:'Cancel'}));assert.equal((await listPhotos('GBT-01')).length,1);fireEvent.click(screen.getByRole('button',{name:'Remove photo'}));fireEvent.click(screen.getByRole('button',{name:'Confirm photo removal'}));await waitFor(()=>assert.ok(screen.getByText('Photo removed from this browser.')));assert.equal((await listPhotos('GBT-01')).length,0);cleanup();dom.window.close();
console.log('PASS: actual photo panel upload, metadata association, reopen, component filtering, locate callback, download, decode failure preservation and confirmed removal. Image decoder is stubbed; browser pixels are not tested.');
