import assert from 'node:assert/strict';
import {siteDefinitions,networkLinks,simulateNetwork,networkScenarios} from './lib/private-network.ts';
import {createPortfolio,siteCondition,parseProject,readPortfolio,designChecks,transition} from './lib/site-model.ts';
const portfolio=createPortfolio();assert.equal(siteDefinitions.length,30);assert.equal(networkLinks.length,38);assert.equal(Object.values(portfolio).reduce((n,p)=>n+p.equipment.length,0),254);
for(const [type,count] of Object.entries({GBT:8,RTT:8,IBS:10,SMALL_CELL:2,CORE:2}))assert.equal(siteDefinitions.filter(s=>s.type===type).length,count);
for(const site of siteDefinitions){const p=portfolio[site.id];assert.equal(parseProject(p).siteId,site.id);assert.equal(designChecks(p).length,0,site.id);assert.equal(siteCondition(p).offline,false,site.id);assert.ok(networkLinks.some(l=>l.a===site.id||l.b===site.id));assert.equal(new Set(p.equipment.map(e=>e.logicalId)).size,p.equipment.length);let revision=transition(p,'approved');revision=transition(revision,'building');revision.work=revision.work.map(w=>({...w,complete:true,note:'Verified sample test evidence.'}));revision=transition(revision,'accepted');assert.equal(revision.baseline.length,p.equipment.length);}
assert.equal(simulateNetwork('normal',100).online,30);assert.equal(simulateNetwork('fiber',100).online,30);const core=simulateNetwork('core',100);assert.equal(core.online,29);assert.ok(core.states.filter(s=>s.status!=='offline').every(s=>s.source==='CORE-02'));assert.equal(simulateNetwork('normal',100,['CORE-01','CORE-02']).online,0);
const ibs='IBS-01';const access=networkLinks.find(l=>l.b===ibs);const cut=simulateNetwork('normal',100,[],[access.id]);assert.equal(cut.states.find(s=>s.id===ibs).status,'offline');assert.notEqual(cut.states.find(s=>s.id==='IBS-02').status,'offline');assert.ok(cut.states.find(s=>s.id==='IBS-02').delivered>=simulateNetwork('normal',100).states.find(s=>s.id==='IBS-02').delivered);
const critical='IBS-05';const criticalAccess=networkLinks.find(l=>l.b===critical);assert.notEqual(simulateNetwork('normal',100,[],[criticalAccess.id]).states.find(s=>s.id===critical).status,'offline');
const partial=structuredClone(portfolio['GBT-01']);partial.equipment.find(e=>e.id==='RRU-A').condition='offline';assert.equal(siteCondition(partial).radioFactor,2/3);for(const e of partial.equipment.filter(e=>e.kind==='radio'))e.condition='offline';assert.equal(siteCondition(partial).offline,true);
const cp=structuredClone(portfolio['CORE-01']);cp.equipment.find(e=>e.id==='GW-A').condition='offline';assert.equal(siteCondition(cp).offline,false);cp.equipment.find(e=>e.id==='GW-B').condition='offline';assert.equal(siteCondition(cp).offline,true);
assert.deepEqual(readPortfolio(JSON.stringify(portfolio)),portfolio);assert.throws(()=>readPortfolio(JSON.stringify({wrong:portfolio['GBT-01']})),/identity/);assert.equal(Object.keys(readPortfolio(JSON.stringify({north:{...portfolio['GBT-01'],siteId:'north',networkId:'north'}}))).length,30);
let cases=0;for(const scenario of networkScenarios)for(const d of [25,100,250])for(const id of siteDefinitions.map(s=>s.id)){const r=simulateNetwork(scenario.id,d,[id]);assert.ok(r.delivered>=0&&r.delivered<=r.requested);assert.ok(Number.isFinite(r.latency));for(const s of r.states){if(s.status==='offline')assert.equal(s.delivered,0);if(s.route)for(const i of s.route)assert.equal(r.broken[i],false);}cases++;}
console.log(`Private network checks passed: 30 sites, 254 assets, 38 links, all-type lifecycle, dual-core failover, ring redundancy, access isolation, hardware degradation, persistence validation, and ${cases} outage/scenario/demand combinations.`);

