import {build} from 'esbuild';
import {JSDOM} from 'jsdom';
import assert from 'node:assert/strict';
import {pathToFileURL} from 'node:url';
import path from 'node:path';
import {surveyBytes} from './survey.test.mjs';
import {getSurvey,removeSurvey} from './lib/survey-store.ts';
import {loadSiteGlb,disposeObject} from './lib/site-geometry.ts';
const dom=new JSDOM('<!doctype html><html><body></body></html>',{url:'http://localhost/sites',pretendToBeVisual:true});
for(const key of ['window','document','navigator','HTMLElement','Element','Node','MutationObserver','HTMLInputElement','HTMLTextAreaElement','getComputedStyle','FormData','Event','MouseEvent','File'])Object.defineProperty(globalThis,key,{value:dom.window[key],configurable:true,writable:true});
globalThis.IS_REACT_ACT_ENVIRONMENT=true;
await build({entryPoints:['components/twin/survey-panel.tsx'],outfile:'.test-survey-bundle.mjs',bundle:true,platform:'node',format:'esm',packages:'external',jsx:'automatic',loader:{'.css':'empty'}});
const React=await import('react'),{render,screen,fireEvent,cleanup,waitFor}=await import('@testing-library/react'),{default:SurveyPanel}=await import(pathToFileURL(path.resolve('.test-survey-bundle.mjs')).href);
let opened=0,designed=0;const props={siteId:'GBT-01',active:false,onOpen:async r=>{const glb=await loadSiteGlb(r.bytes);disposeObject(glb.scene);opened++;},onDesign:()=>designed++};
render(React.createElement(SurveyPanel,props));await waitFor(()=>assert.equal(screen.getByLabelText('Load a GLB site survey model').disabled,false));
fireEvent.click(screen.getByText('Import a site survey'));fireEvent.change(screen.getByLabelText('Survey source'),{target:{value:'Field capture team'}});fireEvent.change(screen.getByLabelText('Capture date'),{target:{value:'2026-09-06'}});
fireEvent.change(screen.getByLabelText('Load a GLB site survey model'),{target:{files:[{name:'field.glb',size:surveyBytes.byteLength,arrayBuffer:async()=>surveyBytes.slice(0)}]}});
await waitFor(()=>assert.ok(screen.getByText('Survey saved for this site and will reopen after reload.')));assert.equal(opened,1);assert.equal((await getSurvey('GBT-01')).source,'Field capture team');
cleanup();render(React.createElement(SurveyPanel,props));await waitFor(()=>assert.ok(screen.getByText('Saved survey restored for this site.')));assert.equal(opened,2);assert.ok(screen.getByText('field.glb'));
fireEvent.click(screen.getByRole('button',{name:'View equipment & cables'}));assert.equal(designed,1);
fireEvent.click(screen.getByText('Replace this site’s survey'));fireEvent.change(screen.getByLabelText('Load a GLB site survey model'),{target:{files:[{name:'invalid.glb',size:8,arrayBuffer:async()=>new ArrayBuffer(8)}]}});await waitFor(()=>assert.ok(screen.getByText('Choose a self-contained GLB smaller than 20 MB.')));assert.equal((await getSurvey('GBT-01')).filename,'field.glb');assert.equal(opened,2);
fireEvent.click(screen.getByRole('button',{name:'Remove survey'}));fireEvent.click(screen.getByRole('button',{name:'Cancel'}));assert.ok(await getSurvey('GBT-01'));fireEvent.click(screen.getByRole('button',{name:'Remove survey'}));fireEvent.click(screen.getByRole('button',{name:'Confirm removal'}));await waitFor(()=>assert.ok(screen.getByText('Survey removed from this browser.')));assert.equal(await getSurvey('GBT-01'),null);
cleanup();render(React.createElement(SurveyPanel,{...props,siteId:'IBS-01'}));await waitFor(()=>assert.equal(screen.getByLabelText('Load a GLB site survey model').disabled,false));assert.ok(screen.getByText('No survey attached'));cleanup();await removeSurvey('GBT-01');dom.window.close();
console.log('Survey controls passed: GLB import with provenance, save, remount restoration, design switch, invalid replacement retention, cancel/confirm removal and another-site isolation. Real GLB parsing used; WebGL pixels not tested.');
