'use client';
/* SVG nodes require SVG groups with keyboard support; HTML buttons cannot be children of SVG. */
/* oxlint-disable jsx-a11y/prefer-tag-over-role */
import { useEffect, useMemo, useState } from 'react';
import Link from 'next/link';
import { Network, RadioTower, Activity, Hospital, School, House, Landmark, Factory, Droplets, TrafficCone, Server, Play, Pause, RotateCcw, ArrowUpRight, ChevronRight, Zap, Cable, CircleHelp, X, Check, Layers, Minus, Plus } from 'lucide-react';
import { Slider } from '@/components/ui/slider';
import { registerSimulationTool } from '@/lib/webmcp';
import { assets, links, scenarios, simulate } from '@/lib/simulation';
const icons:Record<string,typeof Network>={'Core router':Server,'Fiber cabinet':Network,'5G tower':RadioTower,Healthcare:Hospital,Education:School,Residential:House,'Civic service':Landmark,Industry:Factory,'Water utility':Droplets,Transport:TrafficCone};
export default function Home(){
 const [scenario,setScenario]=useState('normal');const [demand,setDemand]=useState(100);const [disabled,setDisabled]=useState<string[]>([]);const [selected,setSelected]=useState('core');const [running,setRunning]=useState(true);const [tick,setTick]=useState(0);const [zoom,setZoom]=useState(1);const [layer,setLayer]=useState('all');const [help,setHelp]=useState(false);
 useEffect(()=>{if(!running)return;const timer=setInterval(()=>setTick(t=>t+1),1500);return ()=>clearInterval(timer);},[running]);
 useEffect(()=>registerSimulationTool((s,d)=>{setScenario(s);setDemand(d);setDisabled([]);setTick(0);}),[]);
 const result=useMemo(()=>simulate(scenario,demand,disabled),[scenario,demand,disabled]);
 const asset=result.states.find(a=>a.id===selected)!; const Icon=icons[asset.type];
 const unhealthy=result.states.filter(a=>a.status!=='online');
 const reset=()=>{setScenario('normal');setDemand(100);setDisabled([]);setTick(0);};
 const changeScenario=(id:string)=>{setScenario(id);setTick(0);};
 return <div className="app-shell">
 <header className="topbar"><Link className="brand" href="/"><span className="brand-icon"><Network size={23}/></span>citymesh<span className="brand-divider"/> <span className="product-label">DIGITAL TWIN</span></Link><div className="header-right"><span className="demo-badge"><span/> Simulation workspace</span><button className="icon-button" onClick={()=>setHelp(!help)} aria-label="About this simulation"><CircleHelp size={20}/></button><span className="avatar">CM</span></div></header>
 <main><div className="heading"><div><div className="eyebrow">CITY OPERATIONS <ChevronRight size={13}/> NETWORK OVERVIEW</div><h1>A connected city. In real time.</h1><p>Explore infrastructure, test disruptions, and understand their impact.</p></div><div className="city-chip"><span className="city-icon"><Landmark size={21}/></span><div><strong>Jangaon · Model city</strong><small>Synthetic topology · 12 infrastructure assets</small></div></div></div>
 {help&&<div className="help"><div><strong>A simulation, with no live infrastructure connection.</strong><p>Traffic follows the shortest available route from the central exchange. Shared link capacity limits throughput. Power failures propagate through network dependencies. One tick represents one simulated minute; demand stays fixed until you change it. Geographic positions are illustrative.</p></div><button aria-label="Close explanation" onClick={()=>setHelp(false)}><X size={20}/></button></div>}
 <section className="metrics" aria-label="Network metrics">{[
 {title:'Network availability',value:result.availability.toFixed(1),unit:'%',note:`${result.online} of ${assets.length} assets reachable`,icon:Network},
 {title:'Delivered throughput',value:(result.delivered/1000).toFixed(2),unit:'Gbps',note:`${(result.requested/1000).toFixed(2)} Gbps requested`,icon:Activity},
 {title:'Average latency',value:result.latency.toFixed(1),unit:'ms',note:'Across reachable service assets',icon:Zap},
 {title:'Assets needing attention',value:String(unhealthy.length).padStart(2,'0'),unit:'',note:unhealthy.length?'Inspect affected infrastructure':'All systems operating normally',icon:RadioTower}
 ].map(m=><article className="metric" key={m.title}><div className="metric-label">{m.title}<m.icon size={17}/></div><div className="metric-value">{m.value}<span>{m.unit}</span></div><small><span className={unhealthy.length?'status-dot amber':'status-dot'}/>{m.note}</small></article>)}</section>
 <div className="workspace"><section className="map-panel"><div className="panel-head"><div><h2>City network</h2><span>Infrastructure & connectivity</span></div><div className="live"><span className={running?'status-dot':'status-dot amber'}/>{running?'Simulation running':'Simulation paused'}</div></div><div className="map-area"><div className="map-tools"><span><Layers size={15}/> Layers</span>{['all','fiber','wireless'].map(l=><button aria-pressed={layer===l} className={layer===l?'active':''} onClick={()=>setLayer(l)} key={l}>{l==='all'?'All assets':l==='fiber'?'Fiber':'Wireless'}</button>)}</div>
 <svg className={'city-map '+(running?'animated':'')} viewBox={`${400-400/zoom} ${305-305/zoom} ${800/zoom} ${610/zoom}`} aria-label="Interactive city infrastructure map">
 <defs><pattern id="grid" width="24" height="24" patternUnits="userSpaceOnUse"><path d="M 24 0 L 0 0 0 24" fill="none" stroke="#e2e9e8" strokeWidth=".7"/></pattern><filter id="shadow"><feDropShadow dx="0" dy="3" stdDeviation="4" floodOpacity=".08"/></filter></defs>
 <rect width="800" height="610" fill="#f3f7f6"/><rect width="800" height="610" fill="url(#grid)"/>
 <path d="M735 -40 C605 75 790 158 714 262 S760 425 835 530" stroke="#c9e6eb" strokeWidth="59" fill="none"/><path d="M735 -40 C605 75 790 158 714 262 S760 425 835 530" stroke="#e8f6f7" strokeWidth="2" fill="none"/>
 <g stroke="#dce4e2" strokeWidth="14" fill="none"><path d="M0 220H800 M0 408H800 M305 0V610 M520 0V610"/><path d="M0 555L800 55"/></g><g stroke="white" strokeWidth="10" fill="none"><path d="M0 220H800 M0 408H800 M305 0V610 M520 0V610"/><path d="M0 555L800 55"/></g>
 <g className="districts"><text x="55" y="75">WEST QUARTER</text><text x="328" y="55">NORTH DISTRICT</text><text x="545" y="67">CIVIC DISTRICT</text><text x="55" y="555">RESIDENTIAL</text><text x="345" y="565">SOUTH DISTRICT</text><text x="612" y="570">INDUSTRIAL ZONE</text></g>
 {layer!=='fiber'&&['north','south'].map(id=>{const a=assets.find(a=>a.id===id)!;return <g key={id} opacity={result.states.find(n=>n.id===id)?.status==='offline'?0.15:1}><circle cx={a.x} cy={a.y} r="84" fill="#6e9ce5" fillOpacity=".055" stroke="#8eaee0" strokeDasharray="4 6"/><circle cx={a.x} cy={a.y} r="58" fill="none" stroke="#afc6e9" strokeOpacity=".5"/></g>;})}
 {links.map((l,i)=>{const a=assets.find(a=>a.id===l.a)!;const b=assets.find(a=>a.id===l.b)!;const wireless=['north','south'].includes(l.b);if(layer==='wireless'&&!wireless)return null; if(layer==='fiber'&&wireless)return null;const color=result.broken[i]?'#e57168':result.loads[i]>l.capacity?'#d69732':wireless?'#7299d6':'#32a68b';return <g key={i}><path d={`M${a.x} ${a.y} L${b.x} ${b.y}`} stroke={color} strokeWidth="2.5" strokeDasharray={result.broken[i]?'6 6':undefined} fill="none"/><path className={!result.broken[i]?'flow':''} d={`M${a.x} ${a.y} L${b.x} ${b.y}`} stroke="white" strokeWidth="2" strokeDasharray="3 32" opacity={result.broken[i]?0:.7}/></g>;})}
 {result.states.map(a=>{const NodeIcon=icons[a.type];return <g key={a.id} role="button" tabIndex={0} aria-label={`${a.name}, ${a.status}`} onClick={()=>setSelected(a.id)} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();setSelected(a.id);}}} className="map-node" opacity={layer==='wireless'&&a.type!=='5G tower'&&a.id!=='core'?.3:1} transform={`translate(${a.x},${a.y})`}><circle r="29" fill={selected===a.id?'#d4ede4':'transparent'} stroke={selected===a.id?'#28a180':'transparent'}/><rect x="-20" y="-20" width="40" height="40" rx="11" fill={a.id==='core'?'#147d63':'white'} stroke={a.status==='offline'?'#e57168':a.status==='degraded'?'#d69732':'#d4dfdc'} filter="url(#shadow)"/><NodeIcon x="-10" y="-10" width="20" height="20" color={a.id==='core'?'white':a.status==='offline'?'#dc6b64':'#45655c'}/><circle cx="16" cy="-16" r="4.5" fill={a.status==='offline'?'#e57168':a.status==='degraded'?'#d69732':'#36aa87'} stroke="white" strokeWidth="2"/><text y="39" textAnchor="middle">{a.name}</text></g>;})}
 </svg><div className="map-bottom"><span className="map-caption">SCHEMATIC VIEW <span>·</span> NOT TO SCALE</span><div className="zoom"><button aria-label="Zoom out" disabled={zoom<=1} onClick={()=>setZoom(Math.max(1,zoom-.2))}><Minus size={16}/></button><button onClick={()=>setZoom(1)} aria-label="Reset map zoom">{Math.round(zoom*100)}%</button><button aria-label="Zoom in" disabled={zoom>=1.6} onClick={()=>setZoom(Math.min(1.6,zoom+.2))}><Plus size={16}/></button></div></div></div><div className="legend"><span><i className="line"/> Fiber link</span><span><i className="line blue"/> Wireless access</span><span><i className="status-dot"/> Operational</span><span><i className="status-dot amber"/> Degraded</span><span><i className="status-dot red"/> Offline</span></div></section>
 <aside className="controls"><section className="scenario-panel"><div className="panel-head"><h2><Zap size={17}/> Scenario lab</h2><span className="mini-badge">WHAT IF</span></div><p className="panel-intro">See how your city responds to change.</p><div className="scenarios">{scenarios.map((s,i)=><button className={'scenario '+(scenario===s.id?'chosen':'')} onClick={()=>changeScenario(s.id)} key={s.id}><span className="scenario-symbol">{i===0?<Activity size={18}/>:i===1?<Cable size={18}/>:i===2?<Zap size={18}/>:i===3?<RadioTower size={18}/>:<ArrowUpRight size={18}/>}</span><span>{s.name}</span>{scenario===s.id?<Check size={16}/>:<ChevronRight size={15}/>}</button>)}</div><p className="scenario-description">{scenarios.find(s=>s.id===scenario)?.description}</p><div className="demand-label"><span id="demand-label">Traffic demand</span><strong>{demand}%</strong></div><Slider aria-labelledby="demand-label" value={[demand]} min={25} max={250} step={5} onValueChange={v=>setDemand(Array.isArray(v)?v[0]:v)}/><div className="range-labels"><span>25% · Low</span><span>250% · Peak</span></div><div className="simulation-buttons"><button className="primary-button" onClick={()=>setRunning(!running)}>{running?<Pause size={15}/>:<Play size={15}/>} {running?'Pause simulation':'Resume simulation'}</button><button className="reset" onClick={reset} aria-label="Reset simulation"><RotateCcw size={17}/></button></div><div className="sim-time">SIMULATED TIME <strong>{String(Math.floor(tick/60)).padStart(2,'0')}:{String(tick%60).padStart(2,'0')}</strong></div></section>
 <section className="asset-panel"><div className="section-kicker">SELECTED ASSET</div><div className="asset-heading"><span className="asset-icon"><Icon size={21}/></span><div><h2>{asset.name}</h2><span>{asset.type} · {asset.zone} district</span></div></div><div className={'asset-status '+asset.status}><span className={'status-dot '+(asset.status==='offline'?'red':asset.status==='degraded'?'amber':'')}/>{asset.status==='online'?'Operational':asset.status==='degraded'?'Capacity constrained':'Disconnected'}</div><dl><div><dt>Throughput</dt><dd>{asset.delivered.toFixed(0)} <span>Mbps</span></dd></div><div><dt>Path latency</dt><dd>{asset.status==='offline'?'—':asset.latency.toFixed(0)} <span>ms</span></dd></div><div><dt>Backup power</dt><dd>{asset.backup?'Available':'Unavailable'}</dd></div></dl><button className="asset-toggle" onClick={()=>setDisabled(disabled.includes(asset.id)?disabled.filter(id=>id!==asset.id):[...disabled,asset.id])}>{disabled.includes(asset.id)?'Restore asset':'Simulate asset failure'}<ArrowUpRight size={16}/></button></section></aside></div>
 <section className="impact"><div><span className="section-kicker">SCENARIO IMPACT</span><h2>{unhealthy.length?`${unhealthy.length} assets affected`:'Your city is connected'}</h2><p>{unhealthy.length?unhealthy.map(a=>a.name).join(' · '):scenario==='fiber'?'West traffic rerouted through East aggregation. Redundancy keeps all assets connected.':'Choose a disruption in the scenario lab to explore network resilience.'}</p></div><div className="impact-stat"><strong>{result.requested?((1-result.delivered/result.requested)*100).toFixed(1):'0.0'}<span>%</span></strong><span>Unserved demand</span></div></section><footer><span><Network size={14}/> CITYMESH <span> / </span> Small-city network digital twin</span><span>Synthetic data · Prototype v1.0</span></footer>
 </main></div>;
}

