import {externalCable} from './cabling.ts';
import {siteById,type Backhaul} from './private-network.ts';
import type {Project} from './site-model.ts';
export type Terrain={minX:number;minZ:number;step:number;width:number;height:number;elevations:number[];reference:number;source:string;retrievedAt:string};
export type CityBuilding={id:number;baseElevation?:number|null;height:number|null;rings:number[][][]};
export type Environment={terrain:Terrain;buildings:CityBuilding[];buildingSource:string;buildingYear:number};
export function ground(t:Terrain,x:number,z:number):number|null{const col=(x-t.minX)/t.step,row=(z-t.minZ)/t.step;if(col<0||row<0||col>t.width-1||row>t.height-1)return null;const i=Math.min(t.width-2,Math.floor(col)),j=Math.min(t.height-2,Math.floor(row)),u=col-i,v=row-j,at=(a:number,b:number)=>t.elevations[b*t.width+a];return at(i,j)*(1-u)*(1-v)+at(i+1,j)*u*(1-v)+at(i,j+1)*(1-u)*v+at(i+1,j+1)*u*v;}
export function buildingInside(b:CityBuilding,x:number,z:number){let inside=false;for(const ring of b.rings)for(let i=0,j=ring.length-1;i<ring.length;j=i++){const a=ring[i],c=ring[j];if((a[1]>z)!==(c[1]>z)&&x<(c[0]-a[0])*(z-a[1])/(c[1]-a[1])+a[0])inside=!inside;}return inside;}
export function buildingBase(t:Terrain,b:CityBuilding){if(typeof b.baseElevation==='number'&&Number.isFinite(b.baseElevation))return b.baseElevation;const r=b.rings[0],x=r.reduce((n,p)=>n+p[0],0)/r.length,z=r.reduce((n,p)=>n+p[1],0)/r.length;return ground(t,x,z);}
export type PathSample={distance:number;x:number;z:number;ground:number;obstacle:number;ray:number;fresnel:number;unknown:boolean};
export function losProfile(env:Environment,link:Backhaul,portfolio:Record<string,Project>,frequencyGHz=18){if(!Number.isFinite(frequencyGHz)||frequencyGHz<=0)throw new Error('Choose a positive microwave frequency');const cable=externalCable(link,portfolio),world=(end:typeof cable.from)=>{const s=siteById(end.siteId)!;const x=(s.x-500)*2.5+end.position[0],z=(s.y-350)*2.5+end.position[2],elevation=ground(env.terrain,(s.x-500)*2.5,(s.y-350)*2.5);if(elevation===null)throw new Error('Endpoint outside the terrain dataset');return {x,z,y:elevation+end.position[1]};},a=world(cable.from),b=world(cable.to),dx=b.x-a.x,dz=b.z-a.z,distance=Math.hypot(dx,dz),fractions=new Set<number>();for(let i=0;i<=Math.ceil(distance/5);i++)fractions.add(i/Math.ceil(distance/5));
 const candidates=env.buildings.filter(building=>{const points=building.rings.flat(),xs=points.map(p=>p[0]),zs=points.map(p=>p[1]);return Math.max(...xs)>=Math.min(a.x,b.x)&&Math.min(...xs)<=Math.max(a.x,b.x)&&Math.max(...zs)>=Math.min(a.z,b.z)&&Math.min(...zs)<=Math.max(a.z,b.z);});
 // Add exact footprint edge crossings and interval midpoints so narrow buildings are not skipped by the terrain sample interval.
 for(const building of candidates){const intersections:number[]=[];for(const r of building.rings)for(let i=0;i<r.length-1;i++){const p=r[i],q=r[i+1],ex=q[0]-p[0],ez=q[1]-p[1],cross=dx*ez-dz*ex;if(Math.abs(cross)<1e-10)continue;const t=((p[0]-a.x)*ez-(p[1]-a.z)*ex)/cross,u=((p[0]-a.x)*dz-(p[1]-a.z)*dx)/cross;if(t>=0&&t<=1&&u>=0&&u<=1){fractions.add(t);intersections.push(t);}}intersections.sort((x,y)=>x-y);for(let i=1;i<intersections.length;i++)fractions.add((intersections[i-1]+intersections[i])/2);}
 const samples:PathSample[]=[...fractions].sort((x,y)=>x-y).map(t=>{const x=a.x+dx*t,z=a.z+dz*t,elevation=ground(env.terrain,x,z);if(elevation===null)throw new Error('Path leaves the terrain dataset');let obstacle=elevation,unknown=false;for(const building of candidates)if(buildingInside(building,x,z)){if(building.height===null)unknown=true;else {const base=buildingBase(env.terrain,building);if(base===null)unknown=true;else obstacle=Math.max(obstacle,base+building.height);}}const bulge=distance*distance*t*(1-t)/(2*(4/3)*6371000),fresnel=Math.sqrt((.299792458/frequencyGHz)*distance*t*(1-t));return {distance:distance*t,x,z,ground:elevation,obstacle:obstacle+bulge,ray:a.y+(b.y-a.y)*t,fresnel,unknown};});const interior=samples.filter(s=>s.distance>0&&s.distance<distance),clearance=Math.min(...interior.map(s=>s.ray-s.obstacle)),fresnelClearance=Math.min(...interior.map(s=>s.ray-s.obstacle-.6*s.fresnel)),unknown=samples.some(s=>s.unknown);return {id:link.id,a,b,distance,samples,clearance,fresnelClearance,unknown,status:clearance<0?'Blocked':unknown?'Unknown heights':fresnelClearance<0?'Fresnel obstructed':'Model clear',frequencyGHz};}
export type LOSProfile=ReturnType<typeof losProfile>;
export function parseEnvironment(terrain:unknown,data:unknown):Environment{const t=terrain as Partial<Terrain>,d=data as {buildings?:CityBuilding[];source?:string;sourceYear?:number};if(!t||!d||!Number.isInteger(t.width)||!Number.isInteger(t.height)||!t.width||!t.height||t.width<2||t.height<2||!Array.isArray(t.elevations)||t.elevations.length!==t.width*t.height||t.elevations.some(v=>!Number.isFinite(v))||![t.minX,t.minZ,t.step,t.reference].every(v=>typeof v==='number'&&Number.isFinite(v))||!t.step||t.step<=0||!Array.isArray(d.buildings)||typeof d.source!=='string'||typeof d.sourceYear!=='number')throw new Error('Incomplete environment dataset');for(const b of d.buildings)if(!Number.isFinite(b.id)||(b.height!==null&&(!Number.isFinite(b.height)||b.height<0))||!Array.isArray(b.rings)||b.rings.length===0||b.rings.some(r=>r.length<4||r.some(p=>p.length<2||!Number.isFinite(p[0])||!Number.isFinite(p[1]))))throw new Error('Invalid building dataset');return {terrain:t as Terrain,buildings:d.buildings,buildingSource:d.source,buildingYear:d.sourceYear};}
