'use client';
import {useMemo,useState} from 'react';
import Link from 'next/link';
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from '@/components/ui/select';
import {buildSiteCabling,cableColors,cableLabels,traceCircuit,type PhysicalCable} from '@/lib/cabling';
import {exportIfc} from '@/lib/ifc-export';
import type {Project} from '@/lib/site-model';
import './cabling.css';
export function CableDetails({cable:c,status}:{cable:PhysicalCable;status?:string}){return <article className="cable-detail"><span className="cable-kind" style={{color:cableColors[c.medium]}}>{cableLabels[c.medium]} · {c.role}</span><h3>{c.label}</h3><code>{c.id}</code>{status&&<p><strong>{status}</strong></p>}<div className="cable-endpoints">{[c.from,c.to].map((end,i)=><div key={i}><small>{i?'B / TO':'A / FROM'} · {end.siteId}</small><strong>{end.assetName}</strong><code>{end.assetId} / {end.port}</code><span>{end.connector}</span></div>)}</div><dl><div><dt>Cable / medium</dt><dd>{c.cable}</dd></div><div><dt>Service</dt><dd>{c.service}</dd></div><div><dt>Estimated length</dt><dd>{c.length} m</dd></div></dl><p>{c.details}</p><small>{c.lengthBasis}. Port names and fittings are illustrative.</small></article>;}
export default function CablingPanel({portfolio,siteId,route,source,selectedCable,onCable}:{portfolio:Record<string,Project>;siteId:string;route:number[]|undefined;source:string|undefined;selectedCable?:string;onCable?:(id:string)=>void}){
 const [exportMessage,setExportMessage]=useState('');const p=portfolio[siteId];const plan=useMemo(()=>buildSiteCabling(p),[p]);const [medium,setMedium]=useState('all'),[target,setTarget]=useState(''),[localSelected,setLocalSelected]=useState('');
 const targets=p.equipment.filter(e=>e.kind==='antenna'||e.kind==='radio');const targetId=targets.some(e=>e.id===target)?target:targets[0]?.id||p.equipment[0]?.id||'';const trace=traceCircuit(portfolio,siteId,targetId,route,source);const chosen=plan.cables.find(c=>c.id===(selectedCable||localSelected));
 const choose=(id:string)=>{setLocalSelected(id);onCable?.(id);};
 return <section className="cabling-workspace"><div className="cabling-heading"><div><small>PHYSICAL CONNECTIVITY / {siteId}</small><h2>From core to antenna. Every termination.</h2><p>Generated wiring design · {plan.cables.length} local connections · {plan.devices.length} illustrative distribution fixtures</p></div><button onClick={()=>{const content=JSON.stringify({siteId,design:'Illustrative; not surveyed',...plan,trace},null,2),url=URL.createObjectURL(new Blob([content],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=`${siteId}-cable-schedule.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}}>Export cable schedule</button><button onClick={async()=>{try{const text=await exportIfc(p,{includeCabling:true});const url=URL.createObjectURL(new Blob([text],{type:"application/x-step"}));const a=document.createElement("a");a.href=url;a.download=`${siteId}-equipment-and-cabling.ifc`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);setExportMessage("IFC4 exported with equipment, cable axes, distribution ports and connection relationships.");}catch(e){setExportMessage(e instanceof Error?e.message:"BIM export failed.");}}}>Export connected BIM · IFC4</button></div>{exportMessage&&<output>{exportMessage}</output>}
 <div className="cabling-columns"><div><h3>Local cable & port schedule</h3><div className="cable-filters">{['all',...Object.keys(cableLabels)].map(m=><button key={m} aria-pressed={medium===m} onClick={()=>setMedium(m)}>{m==='all'?'All cables':cableLabels[m as keyof typeof cableLabels]}</button>)}</div><div className="cable-list">{plan.cables.filter(c=>medium==='all'||c.medium===medium).map(c=><button key={c.id} className={chosen?.id===c.id?'selected':''} onClick={()=>choose(c.id)}><i style={{background:cableColors[c.medium]}}/><span><strong>{c.label}</strong><small>{c.from.assetId} / {c.from.port} → {c.to.assetId} / {c.to.port}</small></span><span>{c.length} m</span></button>)}</div>{chosen?<CableDetails cable={chosen} status={[chosen.from,chosen.to].some(end=>p.equipment.find(e=>e.id===end.assetId)?.condition==="offline")?"Offline endpoint in simulated equipment state":"Design connection · continuity not field-tested"}/>:<p>Select a cable to inspect both termination ports and connectors.</p>}</div>
 <div className="circuit-trace"><h3>End-to-end service trace</h3><label htmlFor="trace-destination">Destination radio / antenna</label><Select value={targetId} onValueChange={v=>{if(v)setTarget(v);}}><SelectTrigger id="trace-destination" aria-label="Trace destination equipment"><SelectValue>{targets.find(a=>a.id===targetId)?.name||"Core LAN"}</SelectValue></SelectTrigger><SelectContent>{targets.length?targets.map(a=><SelectItem value={a.id} key={a.id}>{a.id} · {a.name}</SelectItem>):<SelectItem value={targetId}>Core LAN</SelectItem>}</SelectContent></Select><p><strong>{trace.source}</strong> → <strong>{trace.target}</strong></p>{trace.warning&&<output className="trace-warning">{trace.warning}</output>}<p className="trace-explainer">Ordered physical segments along the active simulated route. Switching, optical/RF conversion and port forwarding occur inside each equipment enclosure between segments.</p><ol>{trace.steps.map((c,i)=><li key={`${i}-${c.id}`}><span className="trace-number" style={{borderColor:cableColors[c.medium]}}>{i+1}</span><div><strong>{c.label}</strong><small>{c.from.siteId} / {c.from.assetId} / {c.from.port}<br/>↓ {c.cable}<br/>{c.to.siteId} / {c.to.assetId} / {c.to.port}</small>{c.from.siteId===siteId&&c.to.siteId===siteId?<button onClick={()=>choose(c.id)}>Inspect termination</button>:<Link href={c.role==='intersite transport'?`/?site=${siteId}&link=${c.id}`:`/sites?site=${c.from.siteId}&cable=${encodeURIComponent(c.id)}`}>Open connection ↗</Link>}</div></li>)}</ol><p className="trace-explainer">Power and grounding are parallel support circuits in the local schedule. This prototype does not calculate optical loss, VSWR, PoE budgets or RF coverage.</p></div></div></section>;
}




