'use client';
/* oxlint-disable react/react-compiler, jsx-a11y/prefer-tag-over-role */
import {useState,useEffect} from 'react';
import Link from 'next/link';
import {siteDefinitions,networkLinks} from '@/lib/private-network';
import {city,siteGeo,mercator,defaultRF,parseRF,defaults,rfFields,eirp,receivedPower,coverageRadius,noiseFloor} from '@/lib/geo-rf';
import './geo-rf.css';
export default function GeoRF({selected,onSite,onLink,broken,offline}:{selected:string;onSite:(id:string)=>void;onLink:(id:string)=>void;broken:boolean[];offline:string[]}){
 const [zoom,setZoom]=useState(15),[offset,setOffset]=useState({x:0,y:0}),[configs,setConfigs]=useState(defaultRF),[ready,setReady]=useState(false),[notice,setNotice]=useState(''),[sample,setSample]=useState(250),[layers,setLayers]=useState(['streets','sites','labels','fiber','ethernet','microwave','coverage']);
 useEffect(()=>{try{const raw=localStorage.getItem('citymesh-rf-v1');if(raw)setConfigs(parseRF(raw));}catch{setNotice('Saved RF settings could not be loaded. Defaults shown.');}setReady(true);},[]);
 useEffect(()=>{if(ready)try{localStorage.setItem('citymesh-rf-v1',JSON.stringify(configs));}catch{setNotice('RF settings could not be saved in this browser.');}},[configs,ready]);
 const c=configs[selected],geo=siteGeo(selected),center=mercator(city.lat,city.lon,zoom),left=center.x-450+offset.x,top=center.y-290+offset.y,scale=256*2**zoom/(40075016.686*Math.cos(city.lat*Math.PI/180));
 const point=(id:string)=>{const g=siteGeo(id),p=mercator(g.lat,g.lon,zoom);return {x:p.x-left,y:p.y-top};};
 const tiles=[];for(let x=Math.floor(left/256);x<=Math.floor((left+900)/256);x++)for(let y=Math.floor(top/256);y<=Math.floor((top+580)/256);y++)tiles.push({x,y});
 const toggle=(l:string)=>setLayers(layers.includes(l)?layers.filter(x=>x!==l):[...layers,l]);
 const area=(id:string,threshold:number)=>{const p=point(id),r=coverageRadius(configs[id],threshold),pts=[];for(let a=0;a<=360;a+=5){const relative=Math.abs(((a-configs[id].azimuth+540)%360)-180),attenuation=Math.min(30,12*(relative/configs[id].beamwidth)**2),d=r*10**(-attenuation/(10*configs[id].exponent))*scale;pts.push(`${p.x+Math.sin(a*Math.PI/180)*d},${p.y-Math.cos(a*Math.PI/180)*d}`);}return pts.join(' ');};
 return <section id="geo-rf" className="geo-rf"><div className="geo-title"><div><h2>Austin · geographic network & RF planning</h2><p>30 hypothetical locations on real geography · no company deployment claimed</p></div><Link href={`/sites?site=${selected}`}>Inspect {selected} in 3D →</Link></div><div className="geo-layout"><div><div className="geo-tools">{['streets','sites','labels','fiber','ethernet','microwave','coverage'].map(l=><label key={l}><input type="checkbox" checked={layers.includes(l)} onChange={()=>toggle(l)}/>{l}</label>)}</div><div className="geo-map"><svg viewBox="0 0 900 580" aria-label="Austin geographic network and estimated RF coverage"><rect width="900" height="580" fill="#e5ece8"/>{layers.includes('streets')&&tiles.map(t=><image key={`${zoom}/${t.x}/${t.y}`} href={`https://tile.openstreetmap.org/${zoom}/${t.x}/${t.y}.png`} x={t.x*256-left} y={t.y*256-top} width="256" height="256" onError={()=>setNotice('Street tiles unavailable. Geographic network overlays remain usable.')}/>)}
 {layers.includes('coverage')&&siteDefinitions.filter(s=>s.type!=='CORE'&&!offline.includes(s.id)).map(s=><g key={s.id} pointerEvents="none">{[configs[s.id].threshold,configs[s.id].threshold+15,configs[s.id].threshold+30].map((v,i)=><polygon key={i} points={area(s.id,v)} fill={['#f6bf43','#49bb97','#2389be'][i]} fillOpacity={s.id===selected?.22:.06} stroke={s.id===selected?['#c68a13','#248569','#17648c'][i]:'none'} strokeWidth="1"/>)}</g>)}
 {networkLinks.map((l,i)=>{if(!layers.includes(l.kind))return null;const a=point(l.a),b=point(l.b);return <g key={l.id} role="button" tabIndex={0} aria-label={`Inspect ${l.id} ${l.kind}`} onClick={()=>onLink(l.id)} onKeyDown={e=>{if(e.key==='Enter')onLink(l.id);}}><line x1={a.x} y1={a.y} x2={b.x} y2={b.y} stroke="transparent" strokeWidth="14"/><line x1={a.x} y1={a.y} x2={b.x} y2={b.y} stroke={broken[i]?'#e44949':l.kind==='microwave'?'#855cc2':l.kind==='fiber'?'#167d77':'#366dd3'} strokeWidth="2.5" strokeDasharray={l.kind==='microwave'?'7 5':undefined}/></g>;})}
 {layers.includes('sites')&&siteDefinitions.map(s=>{const p=point(s.id);return <g key={s.id} role="button" tabIndex={0} aria-label={`Select ${s.id} geographic site`} onClick={()=>onSite(s.id)} onKeyDown={e=>{if(e.key==='Enter')onSite(s.id);}}><circle cx={p.x} cy={p.y} r={s.id===selected?9:6} fill={offline.includes(s.id)?'#d64141':s.type==='CORE'?'#403259':'#173e4b'} stroke="white" strokeWidth="2"/>{layers.includes('labels')&&<text x={p.x+11} y={p.y+4} fontSize="11" fontWeight="700" stroke="white" strokeWidth="3" paintOrder="stroke">{s.id}</text>}</g>;})}</svg><div className="geo-navigation"><button aria-label="Zoom in map" onClick={()=>{setZoom(Math.min(18,zoom+1));setOffset({x:0,y:0});}}>+</button><button aria-label="Zoom out map" onClick={()=>{setZoom(Math.max(13,zoom-1));setOffset({x:0,y:0});}}>−</button>{[['West',-180,0],['East',180,0],['North',0,-120],['South',0,120]].map(([n,x,y])=><button key={n} onClick={()=>setOffset({x:offset.x+Number(x),y:offset.y+Number(y)})}>{n}</button>)}<button onClick={()=>{setZoom(15);setOffset({x:0,y:0});}}>All 30</button></div><a className="geo-attribution" href="https://www.openstreetmap.org/copyright" target="_blank" rel="noreferrer">© OpenStreetMap contributors</a></div><p className="geo-legend">Purple dashed: microwave · teal: fiber · blue: Ethernet · red: failed transport. Coverage: gold ≥ threshold, green +15 dB, blue +30 dB. Overlap is not summed.</p><p>{selected} · {geo.lat.toFixed(6)}° N, {Math.abs(geo.lon).toFixed(6)}° W · <a href={`https://www.openstreetmap.org/?mlat=${geo.lat}&mlon=${geo.lon}#map=17/${geo.lat}/${geo.lon}`} target="_blank" rel="noreferrer">View location</a></p><p>Trunk routes are straight schematic connections, not surveyed underground ducts. IBS contours are illustrative indoor profiles; walls and floors are not mapped.</p></div>
 <aside className="rf-controls"><h3>{selected} · RF parameters</h3>{selected.startsWith('CORE')?<p>Core equipment has no access-radio coverage footprint. Select a GBT, RTT, IBS or small-cell site.</p>:<><div className="rf-kpis"><strong>{eirp(c).toFixed(1)} dBm<small>EIRP</small></strong><strong>{coverageRadius(c).toFixed(0)} m<small>Boresight radius</small></strong></div>{rfFields.map(([key,label,min,max,step])=><label key={key}>{label}<input type="number" min={min} max={max} step={step} value={c[key]} onChange={e=>{if(e.target.value==='')return;const v=Number(e.target.value);if(Number.isFinite(v)&&v>=min&&v<=max)setConfigs({...configs,[selected]:{...c,[key]:v}});}}/></label>)}<label>Probe distance along boresight (m)<input type="number" min="1" max="10000" value={sample} onChange={e=>setSample(Math.max(1,Math.min(10000,Number(e.target.value)||1)))}/></label><output>Received power: <b>{receivedPower(c,sample).toFixed(1)} dBm</b><br/>Noise floor: {noiseFloor(c).toFixed(1)} dBm<br/>Estimated SNR: {(receivedPower(c,sample)-noiseFloor(c)).toFixed(1)} dB<br/>{receivedPower(c,sample)>=c.threshold?'Within':'Outside'} chosen coverage threshold</output><button onClick={()=>setConfigs({...configs,[selected]:defaults(selected)})}>Reset this site RF</button></>}{notice&&<p role="status">{notice}</p>}<details><summary>Model and assumptions</summary><p>Log-distance loss referenced to free-space loss at 1 m: PL = 32.44 + 20 log₁₀(f MHz) − 60 + 10n log₁₀(d metres). Received power = TX + gain − feeder loss − PL − margin − sector attenuation. Sector attenuation = min(30, 12(angular offset / beamwidth)²) dB.</p><p>One equivalent sector per site. These RF settings are separate from the editable physical antenna inventory. No terrain, building blockage, interference, uplink limit or measured calibration. Received power is not RSRP; SNR is not SINR. Settings save in this browser only. Offline network sites omit their service coverage.</p><a href="https://www.itu.int/rec/R-REC-P.525-4-201908-S/en" target="_blank" rel="noreferrer">ITU-R P.525 free-space reference</a></details></aside></div></section>;
}
