'use client';
import {useEffect,useRef,useState} from 'react';
import * as THREE from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {siteDefinitions,networkLinks} from '@/lib/private-network';
import type {Project} from '@/lib/site-model';
import {buildSiteCabling,cableColors,type CableMedium} from '@/lib/cabling';
import {createNetworkModel,siteWorldPosition} from '@/lib/network-geometry';
import {componentLabel} from './component-label';
import {disposeObject} from '@/lib/site-geometry';
type Props={portfolio:Record<string,Project>;selected:string;selectedLink:string|null;selectedCable?:string;selectedAsset?:string;route:number[];broken:boolean[];layer:string;onSite:(id:string)=>void;onLink:(id:string)=>void;onCable:(siteId:string,id:string)=>void;onAsset:(siteId:string,id:string)=>void};
export default function NetworkViewer(props:Props){
 const host=useRef<HTMLDivElement>(null),state=useRef(props),refresh=useRef<()=>void>(()=>{}),rebuild=useRef<()=>void>(()=>{}),reset=useRef<()=>void>(()=>{}),focus=useRef<()=>void>(()=>{});const [error,setError]=useState('');
 useEffect(()=>{state.current=props;refresh.current();},[props]);
 useEffect(()=>{rebuild.current();},[props.portfolio]);
 useEffect(()=>{
  if(!host.current)return;const el=host.current;let renderer:THREE.WebGLRenderer;
  try{renderer=new THREE.WebGLRenderer({antialias:true});}catch{queueMicrotask(()=>setError('WebGL is unavailable. Choose 2D topology or use the cable schedule.'));return;}
  renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.setClearColor('#101f2a');el.appendChild(renderer.domElement);renderer.domElement.setAttribute('aria-label','30-site 3D network. Focus a site to inspect its equipment and cables. Keyboard alternatives are in the directory and cable schedule.');
  const scene=new THREE.Scene(),camera=new THREE.PerspectiveCamera(42,1,.1,15000);scene.add(new THREE.AmbientLight(0xdcefff,2));const sun=new THREE.DirectionalLight(0xffffff,3);sun.position.set(800,1600,600);scene.add(sun);const controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.maxDistance=20000;controls.minDistance=.5;
  let overview=true;controls.addEventListener("start",()=>{overview=false;});const aim=(center:THREE.Vector3,size=35)=>{overview=false;controls.target.copy(center);camera.position.copy(center).add(new THREE.Vector3(size*.9,size*.7,size));controls.update();};reset.current=()=>{const sphere=new THREE.Box3().setFromPoints(siteDefinitions.map(s=>siteWorldPosition(s.id))).expandByScalar(40).getBoundingSphere(new THREE.Sphere());const half=Math.atan(Math.tan(camera.fov*Math.PI/360)*Math.min(1,camera.aspect));controls.target.copy(sphere.center);camera.position.copy(sphere.center).add(new THREE.Vector3(.9,.7,1).normalize().multiplyScalar(sphere.radius/Math.sin(half)*1.12));controls.update();overview=true;};focus.current=()=>aim(siteWorldPosition(state.current.selected).add(new THREE.Vector3(0,11,0)),35);reset.current();
  scene.add(new THREE.GridHelper(2600,52,0x45606b,0x203742));let model:ReturnType<typeof createNetworkModel>|null=null;const labels=new THREE.Group();scene.add(labels);let priorCable='';
  const label=(id:string)=>{const canvas=document.createElement('canvas');canvas.width=256;canvas.height=64;const ctx=canvas.getContext('2d')!;ctx.fillStyle='#11242eee';ctx.fillRect(0,0,256,64);ctx.fillStyle='#e9f3f5';ctx.font='bold 30px sans-serif';ctx.textAlign='center';ctx.fillText(id,128,42);const sprite=new THREE.Sprite(new THREE.SpriteMaterial({map:new THREE.CanvasTexture(canvas),depthTest:false,sizeAttenuation:false}));sprite.scale.set(.07,.0175,1);sprite.userData.siteId=id;return sprite;};
  for(const s of siteDefinitions){const text=label(s.id);text.position.copy(siteWorldPosition(s.id)).add(new THREE.Vector3(0,s.height+5,0));labels.add(text);}
  const focusCable=(id:string)=>{const s=id.split('/')[0],p=state.current.portfolio[s];if(!p)return;const c=buildSiteCabling(p).cables.find(c=>c.id===id);if(!c)return;const a=new THREE.Vector3(...c.from.position),b=new THREE.Vector3(...c.to.position);aim(a.clone().lerp(b,.5).add(siteWorldPosition(s)),Math.max(2,a.distanceTo(b)*.9));};
  refresh.current=()=>{if(!model)return;const p=state.current;networkLinks.forEach((l,i)=>{const line=model!.links.get(l.id)!;line.visible=p.layer==='all'||p.layer===l.kind;(line.material as THREE.LineBasicMaterial).color.set(p.broken[i]?'#ee7777':p.selectedLink===l.id?'#ffffff':p.route.includes(i)?'#f4c76d':l.kind==='microwave'?'#ae91dd':l.kind==='ethernet'?'#6ca9e3':'#49bfac');});for(const [id,mesh] of model.cables)(mesh.material as THREE.MeshBasicMaterial).color.set(id===p.selectedCable?'#ffffff':cableColors[mesh.userData.medium as CableMedium]);for(const [id,mesh] of model.assets)(mesh.material as THREE.MeshStandardMaterial).emissive.set(id===`${p.selected}/${p.selectedAsset}`?'#634916':'#000000');for(const sprite of labels.children as THREE.Sprite[])(sprite.material as THREE.SpriteMaterial).color.set(sprite.userData.siteId===p.selected?'#ffcf78':'#ffffff');if(p.selectedCable&&p.selectedCable!==priorCable)focusCable(p.selectedCable);priorCable=p.selectedCable||'';};
  rebuild.current=()=>{if(model){scene.remove(model.group);disposeObject(model.group);}model=createNetworkModel(state.current.portfolio);for(const s of siteDefinitions){const detail=model.lods.get(s.id)!.levels[0].object;let index=0;for(const e of [...state.current.portfolio[s.id].equipment,...buildSiteCabling(state.current.portfolio[s.id]).devices])detail.add(componentLabel(`${e.id} · ${e.name}`,new THREE.Vector3(...e.position),index++,e.id.startsWith("W-")?{siteId:s.id,cableId:buildSiteCabling(state.current.portfolio[s.id]).cables.find(c=>c.from.assetId===e.id||c.to.assetId===e.id)?.id}:{siteId:s.id,assetId:e.id}));}scene.add(model.group);refresh.current();};rebuild.current();
  const ray=new THREE.Raycaster(),pointer=new THREE.Vector2();let down=[0,0];const start=(e:PointerEvent)=>{down=[e.clientX,e.clientY];};const click=(e:PointerEvent)=>{if(!model||Math.hypot(e.clientX-down[0],e.clientY-down[1])>5)return;const r=el.getBoundingClientRect();pointer.set((e.clientX-r.left)/r.width*2-1,-(e.clientY-r.top)/r.height*2+1);ray.setFromCamera(pointer,camera);ray.params.Line.threshold=Math.max(.08,controls.target.distanceTo(camera.position)*.002);for(const lod of model.lods.values())lod.update(camera);const pickables:THREE.Object3D[]=[];for(const root of [model.group,labels])root.traverseVisible(o=>{if(o instanceof THREE.Mesh||o instanceof THREE.Line||o instanceof THREE.Sprite)pickables.push(o);});const hit=ray.intersectObjects(pickables,false)[0];if(!hit)return;const data=hit.object.userData;if(data.linkId)state.current.onLink(data.linkId);else if(data.cableId){state.current.onCable(data.siteId,data.cableId);focusCable(data.cableId);}else if(data.assetId){state.current.onAsset(data.siteId,data.assetId);aim(hit.object.getWorldPosition(new THREE.Vector3()),5);}else if(data.siteId){state.current.onSite(data.siteId);aim(siteWorldPosition(data.siteId).add(new THREE.Vector3(0,11,0)),35);}};
  renderer.domElement.addEventListener('pointerdown',start);renderer.domElement.addEventListener('pointerup',click);const resize=()=>{renderer.setSize(el.clientWidth,el.clientHeight);camera.aspect=el.clientWidth/Math.max(el.clientHeight,1);camera.updateProjectionMatrix();if(overview)reset.current();};const observer=new ResizeObserver(resize);observer.observe(el);resize();let frame=0;const animate=()=>{frame=requestAnimationFrame(animate);controls.update();renderer.render(scene,camera);};animate();
  return()=>{cancelAnimationFrame(frame);observer.disconnect();controls.dispose();renderer.domElement.removeEventListener('pointerdown',start);renderer.domElement.removeEventListener('pointerup',click);disposeObject(scene);renderer.dispose();renderer.domElement.remove();refresh.current=()=>{};rebuild.current=()=>{};};
 },[]);
 return <div className="network-3d"><div ref={host} className="network-3d-host"/>{error&&<p role="alert">{error}</p>}<div className="network-3d-navigation"><button onClick={()=>focus.current()}>Focus {props.selected}</button><button onClick={()=>reset.current()}>Show all 30 sites</button></div><div className="network-3d-note">Click a site to inspect its equipment and local cables in this map.<br/>Click equipment or cabling for details · scroll to zoom · drag to orbit<br/>Site geometry in metres · schematic campus placement · distant sites use simplified shapes</div></div>;
}

