'use client';
import {useEffect,useState} from 'react';
import type {Project} from '@/lib/site-model';
import {validatePortfolio,type SharedSnapshot} from '@/lib/shared-portfolio';
import PortfolioHistory from './portfolio-history';
import './shared-portfolio.css';
async function readResponse(response:Response):Promise<SharedSnapshot>{const raw=await response.json();if(!raw||typeof raw!=='object')throw new Error('Invalid shared-store response.');const data=raw as Record<string,unknown>;if(!response.ok)throw new Error(typeof data.error==='string'?data.error:'Shared storage unavailable.');if(!Number.isSafeInteger(data.version)||Number(data.version)<0||typeof data.updatedAt!=='string')throw new Error('Invalid shared version response.');return {version:data.version as number,updatedAt:data.updatedAt,projects:data.projects?validatePortfolio(data.projects):null};}
type Props={projects:Record<string,Project>;onLoad:(projects:Record<string,Project>)=>void};
export default function SharedPortfolioPanel({projects,onLoad}:Props){
 const [remote,setRemote]=useState<SharedSnapshot|null>(null),[base,setBase]=useState<number|null>(null),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 const refresh=async()=>{setBusy(true);try{const response=await fetch('/api/portfolio',{cache:'no-store'});const data=await readResponse(response);if(data.projects)validatePortfolio(data.projects);setRemote(data);setMessage(data.version===0?'No shared portfolio yet. Publish the current 30 sites to begin.':`Shared version ${data.version} is available. Loading it replaces this browser’s portfolio; export local edits first.`);}catch(e){setMessage(e instanceof Error?e.message:'Shared storage unavailable.');}finally{setBusy(false);}};
 useEffect(()=>{let cancelled=false;fetch('/api/portfolio',{cache:'no-store'}).then(async r=>{const data=await readResponse(r);if(data.projects)validatePortfolio(data.projects);if(!cancelled)setRemote(data);}).catch(e=>{if(!cancelled)setMessage(e instanceof Error?e.message:'Shared storage unavailable.');});return()=>{cancelled=true;};},[]);
 return <section className="shared-portfolio"><div><small>SHARED PROJECT STORE</small><strong>{remote?remote.version?`Shared portfolio · v${remote.version}`:'Ready for first shared publish':'Connecting to shared storage'}</strong><p>Publish all 30 sites for access from another device. Browser edits stay local until published. Survey GLBs are separate.</p>{base!==null&&<span>Next publish checks shared v{base}</span>}</div><div className="shared-actions"><button disabled={busy} onClick={refresh}>Refresh shared status</button><button disabled={busy||!remote?.projects} onClick={()=>{if(!remote?.projects)return;try{const p=validatePortfolio(remote.projects);onLoad(p);setBase(remote.version);setMessage(`Shared version ${remote.version} loaded into this browser.`);}catch(e){setMessage(e instanceof Error?e.message:'Unable to load shared portfolio.');}}}>Load shared portfolio</button><button disabled={busy||!remote||(remote.version!==0&&base===null)} onClick={async()=>{if(!remote)return;setBusy(true);try{const expectedVersion=base??0;const response=await fetch('/api/portfolio',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({expectedVersion,projects})});if(response.status===409){setBase(null);setRemote(null);}const data=await readResponse(response);setBase(data.version);setRemote({version:data.version,updatedAt:data.updatedAt,projects:structuredClone(projects)});setMessage(`Published shared version ${data.version}. Other devices can now load it.`);}catch(e){setMessage(e instanceof Error?e.message:'Publishing failed. Your browser edits remain available.');}finally{setBusy(false);}}}>{busy?'Working…':'Publish browser portfolio'}</button></div>{message&&<output>{message}</output>}{remote&&remote.version>0&&base===null&&<small className="shared-hint">Load the shared portfolio before publishing changes. A stale version will be rejected.</small>}{remote&&<PortfolioHistory projects={projects} onRestore={(next,version)=>{onLoad(next);setBase(remote.version);setMessage(`Shared revision ${version} restored to this browser. Publish to create a new shared version.`);}}/>}</section>;
}


