'use client';
import Link from '@/components/twin/site-link';
import {useEffect,useState} from 'react';
import {defaultRF,parseRF,eirp,noiseFloor,rfFields} from '@/lib/geo-rf';
import {inventorySectors,sectorGroundRadius,probeSite} from '@/lib/inventory-rf';
import type {Project} from '@/lib/site-model';
export default function SiteRF({project,selected,onSelect,offline=false}:{project:Project;selected:string;onSelect:(id:string)=>void;offline?:boolean}){
 const [configs,setConfigs]=useState(defaultRF),[distance,setDistance]=useState(250),[bearing,setBearing]=useState(0),[notice,setNotice]=useState('');
 useEffect(()=>{const load=()=>{try{const raw=localStorage.getItem('citymesh-rf-v1');setConfigs(raw?parseRF(raw):defaultRF());setNotice('');}catch{setNotice('Saved RF settings unavailable; showing planning defaults.');}};load();window.addEventListener('focus',load);window.addEventListener('storage',load);return()=>{window.removeEventListener('focus',load);window.removeEventListener('storage',load);};},[]);
 const c=configs[project.siteId],sectors=inventorySectors(project,offline),active=sectors.filter(s=>s.active),radius=Math.max(0,...active.map(s=>sectorGroundRadius(c,s,c.threshold,s.bearing))),probe=probeSite(c,sectors,distance,bearing);
 return <section className="site-rf" aria-label="Site RF parameters"><h3>{project.siteId} · RF parameters</h3>{project.siteId.startsWith('CORE')?<p>Core transport equipment has no access-radio coverage. RF parameters are not applicable.</p>:<><p>Planning estimates · saved geographic RF profile</p><div className="site-rf-kpis"><div><strong>{eirp(c).toFixed(1)} dBm</strong><small>EIRP per radio</small></div><div><strong>{radius.toFixed(0)} m</strong><small>Max active coverage radius</small></div></div><dl>{rfFields.filter(([key])=>key!=='azimuth').map(([key,label])=><div key={key}><dt>{label}</dt><dd>{c[key]}</dd></div>)}</dl><h4>Antenna branches · {active.length}/{sectors.length} active</h4>{sectors.map(s=><button className="rf-branch" aria-pressed={selected===s.id} key={s.id} onClick={()=>onSelect(s.id)}><strong>{s.id} ← {s.radioId||'Unmapped radio'}</strong><span>{s.omni?'Omnidirectional':`${s.bearing.toFixed(0)}° true north`} · {s.position[1]} m height</span><span>{s.active?'Active':s.reason} · {s.splitLoss.toFixed(1)} dB splitter loss</span></button>)}<h4>Signal strength probe</h4><label>Distance from site (m)<input type="number" min="1" max="10000" value={distance} onChange={e=>setDistance(Math.max(1,Math.min(10000,Number(e.target.value)||1)))}/></label><label>Bearing (° true north)<input type="number" min="0" max="359" value={bearing} onChange={e=>setBearing(Math.max(0,Math.min(359,Number(e.target.value)||0)))}/></label><output>{probe?`${probe.id}: ${probe.power.toFixed(1)} dBm received power · ${(probe.power-noiseFloor(c)).toFixed(1)} dB SNR · ${probe.power>=c.threshold?'Within':'Outside'} coverage threshold`:'No active antenna branch available.'}</output><p>Noise floor: {noiseFloor(c).toFixed(1)} dBm. Values are modeled, not measurements or RSRP/SINR. Terrain, buildings and interference are excluded; IBS walls and floors are not modeled.</p><Link href="/#geo-rf">Edit RF profiles on geographic planner →</Link></>}{notice&&<output>{notice}</output>}</section>;
}

