'use client';
import {useEffect,useRef,useState} from 'react';
import {getSurvey,makeSurvey,saveSurvey,removeSurvey,type SurveyRecord} from '@/lib/survey-store';
import './survey.css';
type Props={siteId:string;onOpen:(record:SurveyRecord)=>Promise<void>;onDesign:()=>void;active:boolean};
export default function SurveyPanel({siteId,onOpen,onDesign,active}:Props){
 const actions=useRef({onOpen,onDesign});useEffect(()=>{actions.current={onOpen,onDesign};},[onOpen,onDesign]);
 const [record,setRecord]=useState<SurveyRecord|null>(null),[busy,setBusy]=useState(true),[message,setMessage]=useState(''),[saved,setSaved]=useState(false),[confirmRemove,setConfirmRemove]=useState(false);
 useEffect(()=>{let cancelled=false;getSurvey(siteId).then(async value=>{if(cancelled)return;if(value){setRecord(value);setSaved(true);await actions.current.onOpen(value);if(!cancelled)setMessage('Saved survey restored for this site.');}}).catch(e=>{if(!cancelled)setMessage(e instanceof Error?e.message:'Unable to restore survey.');}).finally(()=>{if(!cancelled)setBusy(false);});return()=>{cancelled=true;};},[siteId]);
 const download=(blob:Blob,name:string)=>{const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
 return <section className="survey-panel"><div className="survey-heading"><div><small>SITE CAPTURE / {siteId}</small><h3>Survey model library</h3></div><span>{record?(saved?'Saved in this browser':'Session only'):'No survey attached'}</span></div>
 <p>Attach a self-contained GLB from your survey or modeling tool. Use metre units; geometry is not automatically aligned or mapped to the equipment inventory.</p>
 {record&&<div className="survey-record"><strong>{record.filename}</strong><span>{(record.bytes.byteLength/1024/1024).toFixed(2)} MB · {record.source||'Source not specified'} · {record.capturedAt||'Capture date not specified'}</span><small>SHA-256: {record.sha256}</small>{record.note&&<p>{record.note}</p>}<div className="survey-actions"><button disabled={busy} aria-pressed={active} onClick={async()=>{setBusy(true);try{await actions.current.onOpen(record);setMessage('Survey model opened.');}catch(e){setMessage(e instanceof Error?e.message:'Unable to open survey.');}finally{setBusy(false);}}}>View survey</button><button disabled={busy} aria-pressed={!active} onClick={()=>actions.current.onDesign()}>View equipment & cables</button><button onClick={()=>download(new Blob([record.bytes],{type:'model/gltf-binary'}),record.filename)}>Download GLB</button><button onClick={()=>{const {bytes,...metadata}=record;download(new Blob([JSON.stringify({...metadata,byteLength:bytes.byteLength},null,2)],{type:'application/json'}),`${siteId}-survey-manifest.json`);}}>Export provenance</button><button disabled={busy} onClick={()=>setConfirmRemove(!confirmRemove)}>Remove survey</button></div>{confirmRemove&&<div className="survey-remove"><p>Remove the saved survey for {siteId}? Equipment and cabling remain available.</p><button disabled={busy} onClick={async()=>{setBusy(true);try{await removeSurvey(siteId);actions.current.onDesign();setRecord(null);setSaved(false);setConfirmRemove(false);setMessage('Survey removed from this browser.');}catch(e){setMessage(e instanceof Error?e.message:'Unable to remove survey.');}finally{setBusy(false);}}}>Confirm removal</button><button onClick={()=>setConfirmRemove(false)}>Cancel</button></div>}</div>}
 <details><summary>{record?'Replace this site’s survey':'Import a site survey'}</summary><form key={record?.addedAt||"empty"} onSubmit={e=>e.preventDefault()}><div className="survey-fields"><label>Survey source<input name="source" maxLength={240} placeholder="Survey company, scanner or modeling tool" defaultValue={record?.source||''}/></label><label>Capture date<input name="capturedAt" type="date" defaultValue={record?.capturedAt||''}/></label></div><label>Provenance / accuracy notes<textarea name="note" maxLength={2000} placeholder="Coordinate reference, capture method and known limitations" defaultValue={record?.note||''}/></label><label className="survey-upload">{busy?'Processing survey…':'Choose GLB · up to 20 MB'}<input type="file" accept=".glb" aria-label="Load a GLB site survey model" disabled={busy} onChange={async e=>{const file=e.target.files?.[0],form=e.target.form;e.target.value='';if(!file||!form)return;const data=new FormData(form);const text=(key:string)=>{const value=data.get(key);return typeof value==="string"?value.trim():"";};setBusy(true);setMessage('');try{if(file.size>20*1024*1024)throw new Error('Choose a self-contained GLB smaller than 20 MB.');const next=await makeSurvey(siteId,file.name,await file.arrayBuffer(),{source:text('source'),capturedAt:text('capturedAt'),note:text('note')});await actions.current.onOpen(next);setRecord(next);setSaved(false);setConfirmRemove(false);try{await saveSurvey(next);setSaved(true);setMessage('Survey saved for this site and will reopen after reload.');}catch(e){setMessage(`Model opened for this session, but could not be saved. ${e instanceof Error?e.message:''} Any previously saved survey remains in storage.`);}}catch(e){setMessage(e instanceof Error?e.message:'Unable to import survey.');}finally{setBusy(false);}}}/></label></form></details>
 {message&&<output>{message}</output>}<small className="survey-local-note">Files stay in this browser and are separate from project JSON and IFC exports. Download the GLB and provenance before clearing browser data or moving devices.</small></section>;
}


